---
title: "03-O-ana-Making-a-population-map"
author: "Patrick Green & Pietro Viacava"
date: "27-03-2019"
output: html_document
---

## Load packages
```{r message = FALSE}
library(ggplot2)
library(maps)
```

##extract map of Australia (or any other country/region) border points
```{r}
world_map <- map_data("world")
australia <- subset(world_map, world_map$region=="Australia")
australia
```

##create a base plot with ggplot2
```{r}
bp <- ggplot() + coord_fixed() +
  xlab("") + ylab("")
```

##Add map to base plot
```{r}
australia_messy <- bp + geom_polygon(data=australia, aes(x=long, y=lat, group=group), 
                                     colour="black", fill="white")
australia_messy
```



##read GPS coordinates
```{r}
LatLontest <- read.csv("../1_Data (original data)/1_Raw/03_O_ana_-_All_Landmarked_Metadata.csv", header = T)
LatLontest
```

#plot data points in map
```{r}
australiamap_data <- 
 australia_messy +
  geom_point(data=LatLontest, 
             aes(x=Longitude, y=Latitude), colour="Black", 
             fill="Black",pch=21, size=2, alpha=I(.8))

australiamap_data
```


#If gridline removal is wanted
```{r}
cleanup <- 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        panel.background = element_rect(fill = 'white', colour = 'white'), 
        axis.line = element_line(colour = "white"), legend.position="none",
        axis.ticks=element_blank(), axis.text.x=element_blank(),
        axis.text.y=element_blank())

australia_clean <- australia_messy + cleanup

australia_clean
```
